install:
- npm install
branches:
  only:
  - master
language: node_js
sudo: false
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 118.24.62.205\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_script:
- git pull origin master
after_success:
- scp -r stricthostkeychecking=no /. root@118.24.62.205:/home/test/server
- rsync av -e ssh stricthostkeychecking=no --exclude="node_modules"  b.text root@118.24.62.205:/home/www/server
- pm2 restart all

